- prince-archiver/README.md
- prince-archiver/compose.dev.yml
- prince-archiver/compose.prod.yml
- prince-archiver/compose.yml
- prince-archiver/poetry.lock
- prince-archiver/prince_archiver/celery/__init__.py
- prince-archiver/prince_archiver/config.py
- prince-archiver/prince_archiver/logging.yml
- prince-archiver/pyproject.toml
Clean up docker compose files and update `README.md` accordingly. Allow integration of datadog and sentry.
- Load sentry sdk on loading of config
- Add datadog docker integration for prod
- Ensure celery app configures logging via signal
> prince-archiver: Clean up docker compose files

- prince-archiver/compose.prod.yml
- prince-archiver/poetry.lock
- prince-archiver/prince_archiver/config.py
- prince-archiver/prince_archiver/data_archive/__init__.py
- prince-archiver/prince_archiver/data_archive/archiver.py
- prince-archiver/prince_archiver/data_archive/worker.py
- prince-archiver/pyproject.toml
Add ssh client for connecting to the data archive
- Add `data_archive` sub module
- Add cron worker which ssh's to data archive
- Refactor settings, be explicit with what needs what
> prince-archiver: Add ssh client

- prince-archiver/compose.dev.yml
- prince-archiver/compose.prod.yml
- prince-archiver/compose.yml
- prince-archiver/poetry.lock
- prince-archiver/prince_archiver/worker.py
- prince-archiver/pyproject.toml
Limit number of concurrent jobs  to prevent overwhelming the worker.
- Update `WorkerSettings` adding `max_jobs=2`
- Add replicas to compose to prevent downtime
- Remove `celery` depedence of `sentry-sdk`
> prince-archiver: Limit worker concurrent jobs

- prince-archiver/Dockerfile
- prince-archiver/pyproject.toml
Poetry needs to install the root project in order to symlink the entry points
- Copy application across and install in separate step to dependency installation (for caching reasons)
> prince-archiver: Update Dockerfile

- prince-archiver/prince_archiver/data_archive/handlers.py
Fix types
- Ensure enough arguments passed to log call
> prince-archiver: Bug fixes

- prince-archiver/prince_archiver/data_archive/handlers.py
- prince-archiver/prince_archiver/test_utils/cli.py
- prince-archiver/prince_archiver/test_utils/mock_prince.py
- prince-archiver/tests/e2e/steps/upload.py
Perform object store deletion in chunks
- perform bulk deletion in chunks
- Use `Semaphore` to prevent to many simultaneous requests
> prince-archiver: Delete in chunks

- .github/workflows/prince-archiver.yaml
- prince-archiver/prince_archiver/data_archive/handlers.py
- prince-archiver/prince_archiver/data_archive/subscriber.py
- prince-archiver/prince_archiver/data_archive/worker.py
- prince-archiver/prince_archiver/dto.py
- prince-archiver/prince_archiver/upload_worker/handlers.py
- prince-archiver/scripts/run-e2e-tests.sh
- prince-archiver/tests/compose.integration.yml
- prince-archiver/tests/e2e/steps/upload.py
- prince-archiver/tests/integration/test_subscriber.py
- prince-archiver/tests/unit/conftest.py
- prince-archiver/tests/unit/data_archive/test_handlers.py
- prince-archiver/tests/unit/test_dto.py
- prince-archiver/tests/unit/upload_worker/test_handlers.py
- prince-archiver/tests/unit/upload_worker/test_worker.py
Add integration and unit tests. Ensure pipelines run only on branches with an open PR. 
- Integration tests for data archive subscriber
- Unit tests for:
- Data archive handlers
- Upload worker handlers
- Upload worker workers
- Root dto's
> prince-archiver: Increase test coverage

- .gitignore
- prince-archiver/prince_archiver/data_archive/subscriber.py
Ensure robust rabbitmq connection
- Use `connect_robust` instead of `connect`
> prince-archiver: Use robust rabbitmq connection

- .github/workflows/publish-docker-image.yaml
- .github/workflows/publish.yaml
Push image to docker hub on tagging
- Add `publish-docker-image.yml` workflow
> prince-archiver: Push image to docker hub

- .github/workflows/publish-docker-image.yaml
Strip prefix from docker tag
- add `tags` attritibute to `metadata-action` step.
> add prefix

- .github/workflows/publish-docker-image.yaml
Use regex expression
- use `type=match`
> prince-archiver: Update publish workflow

- prince-archiver/prince_archiver/data_archive/handlers.py
- prince-archiver/prince_archiver/data_archive/worker.py
- prince-archiver/prince_archiver/service_layer/messagebus.py
- prince-archiver/prince_archiver/service_layer/messages.py
- prince-archiver/prince_archiver/upload_worker/handlers.py
- prince-archiver/prince_archiver/upload_worker/worker.py
- prince-archiver/prince_archiver/watcher/context.py
- prince-archiver/prince_archiver/watcher/handlers.py
- prince-archiver/tests/unit/data_archive/test_handlers.py
- prince-archiver/tests/unit/test_messagebus.py
- prince-archiver/tests/unit/upload_worker/test_worker.py
Add messages into service layer
- Add messages into `service_layer` module
- Move message bus to service layer
> prince_archiver: Add messages

- prince-archiver/prince_archiver/service_layer/handlers/exporter.py
- prince-archiver/tests/unit/conftest.py
- prince-archiver/tests/unit/handlers/test_exporter.py
- prince-archiver/tests/unit/handlers/utils.py
Add export handlers.
- Add handlers for exporting data
- Add unit tests
> prince-archiver: Add export handlers

- prince-archiver/prince_archiver/service_layer/exceptions.py
- prince-archiver/prince_archiver/service_layer/handlers/exporter.py
- prince-archiver/prince_archiver/service_layer/handlers/importer.py
- prince-archiver/prince_archiver/service_layer/handlers/utils.py
- prince-archiver/tests/unit/handlers/conftest.py
- prince-archiver/tests/unit/handlers/test_exporter.py
- prince-archiver/tests/unit/handlers/test_importer.py
Add import handlers
- Add `import_imaging_event` and `propagate_new_imaging_event` event handlers
- Add `ServiceLayerException`
- Add unit tests
> prince-archiver: Add import handlers

- prince-archiver/compose.dev.yml
- prince-archiver/compose.prod.yml
- prince-archiver/compose.yml
- prince-archiver/config/traefik.toml
- prince-archiver/prince_archiver/entrypoints/api/app.py
- prince-archiver/prince_archiver/entrypoints/api/dependencies.py
- prince-archiver/prince_archiver/entrypoints/api/models.py
- prince-archiver/prince_archiver/entrypoints/api/routes.py
Add Rest API with `health` and `exports` endpoint. Use Traefik as a reverse proxy in deployments.
- Add basic app in `prince_archiver.entrypoints.api`
- Update docker compose file adding api and traefik
> prince-archiver: Add api

- prince-archiver/prince_archiver/service_layer/handlers/archive.py
- prince-archiver/prince_archiver/service_layer/messages.py
- prince-archiver/prince_archiver/service_layer/uow.py
- prince-archiver/tests/unit/handlers/test_archive.py
- prince-archiver/tests/unit/handlers/utils.py
Add data archive service layer logic.
- Add messages
- Add handlers
- Add repo to retrieve data archive entries
- Add unit tests
> prince-archiver: Add data archive service layer logic

- prince-archiver/prince_archiver/config.py
- prince-archiver/prince_archiver/entrypoints/upload_worker/__init__.py
- prince-archiver/prince_archiver/entrypoints/upload_worker/worker.py
- prince-archiver/prince_archiver/service_layer/handlers/exporter.py
- prince-archiver/prince_archiver/service_layer/messagebus.py
- prince-archiver/tests/unit/upload_worker/test_worker.py
Add v2 upload worker 
- Rename `WorkerSettings` -> `UploadWorkerSettings` for clarity
- Add key generator function
- Add factory method for generating message bus
> prince-archiver: add v2 upload-worker

- prince-archiver/compose.dev.yml
- prince-archiver/poetry.lock
- prince-archiver/prince_archiver/entrypoints/upload_worker/worker.py
- prince-archiver/pyproject.toml
- prince-archiver/tests/unit/test_upload_worker.py
Add retry logic incase of timeouts from object store
- Catch exceptions relating to `OSError` and `ConnectTimeoutError`
- The latter comes from `botocore` though raised by `aiobotocore`
> prince-archiver: Add retry logic

- prince-archiver/compose.yml
Ensure redis persists data
- Add volume
> DA-36 prince-archiver: Persist redis

- prince-archiver/compose.dev.yml
- prince-archiver/compose.prod.yml
- prince-archiver/compose.yml
Update compose files to reflect new entry points
- update `compose.yml`, `compose.dev.yml`, `compose.prod.yml`
> DA-33: Update compose files

- prince-archiver/README.md
- prince-archiver/compose.dev.yml
- prince-archiver/scripts/init-dev.sh
- prince-archiver/scripts/init-localstack.sh
Move from adbove `s3Mock` to `localstack`
- Update `compose.dev.yml` file
- Add init script
> DA-46 prince-archiver: Use local stack

- .github/workflows/publish-docker-image.yaml
- prince-archiver/compose.dev.yml
- prince-archiver/compose.yml
- prince-archiver/scripts/init-dev.sh
Improve prestart behave and naming of docker images
- Update workflow to publish docker image
- Update `compose.yml` reflecting image name
- Rename `db-migrations` to `prestart` and add as dependencies.
> DA-47 prince-archiver: Update compose

- alloy-monitoring/compose.yml
Remove network definition from compose
- remove `networks`
> DA-50 alloy: Remove network definition

- prince-archiver/compose.prod.yml
Ensure aws variables added to `state-manager` in `compose.prod.yml`
- Add variables
> DA-51 prince-archiver: Fix typo

- prince-archiver/compose.prod.yml
- prince-archiver/scripts/backup-db.sh
Add logging to `api` and `aws-cli` services
- Extend services by merging `log-labels` mapping
- Remove network definition
> DA-52: Update prod compose

- prince-archiver/README.md
- prince-archiver/prince_archiver/adapters/archiver.py
Typer needs option to come before argument.
- Specify `--job_id=...` before date argument
> DA-58 prince-archiver: Fix cli call

- .github/workflows/publish-python-package.yaml
- surf-archiver/Dockerfile
Update `Dockerfile` to use python 3.12
- Update `Dockerfile`
- Update publish workflow
> DA-64 surf-archiver: Update python version

- surf-archiver/compose.prod.yml
- surf-archiver/compose.yml
- surf-archiver/poetry.lock
- surf-archiver/pyproject.toml
- surf-archiver/surf_archiver/remote/__init__.py
Add sentry for remote worker
- Install `sentry_sdk` and call within `surf_archvier.remote`
- Update docker compose files
> surf-archiver: Add sentry

- surf-archiver/compose.yml
- surf-archiver/scripts/entrypoint.sh
- surf-archiver/surf_archiver/log.py
- surf-archiver/surf_archiver/remote/worker.py
Fix remote access to `mock-data-archive`
- Grant user rw access to `/data` folder
- Keep env variables fixed
- Add logging for remote
> DA-65 surf-archiver: Fix dev setup

- surf-archiver/README.md
- surf-archiver/development.md
- surf-archiver/pyproject.toml
- surf-archiver/surf_archiver/cli.py
- surf-archiver/surf_archiver/config.py
- surf-archiver/surf_archiver/remote/client.py
- surf-archiver/surf_archiver/remote/worker.py
Enable archiving of videos
- Ensure remote client accepts `mode` argument
- Needed to create `ArchvierCron` class to make sure that cron functions work with mypy
- (needs `__qualname__` which prevents `functools.partial`)
- Update `Readme.md`
- Change CLI entrypoint from `surf-archiver` to surf-archvier-cli`
> DA-81 surf-archiver: Facilitate remote archiving of videos 

- surf-archiver/pyproject.toml
> DA-83 surf-archiver: Bump version

- infrastructure/redis/compose.yml
- infrastructure/redis/scripts/backup.sh
- prince-archiver/compose.prod.yml
- prince-archiver/compose.yml
- prince-archiver/scripts/backup-db.sh
- surf-archiver/compose.prod.yml
Ensure the that `host.docker.internal` is added where calls made to ports on local machine. Clean up backup scripts.
- Add `extra_hosts` to `surf-archiver`' s `compose.prod.yml`
- Correct volume mounts for `aws-cli` containers
> DA-86: Update compose files

- .github/workflows/prince-archiver.yaml
- prince-archiver/Dockerfile
- prince-archiver/compose.aretha.yml
- prince-archiver/prince_archiver/entrypoints/purger/functions.py
- prince-archiver/tests/unit/test_delete_src.py
Add compose for Aretha + fix for purger
- Ensure coroutine awaited within purger function
- Add tests for purger function
- Add config for Aretha
- Update Dockerfile to use capitals
- Update actions workflow to ensure e2e tests run
> DA-88 prince-archiver: Add config

- export-ingester/export_ingester/worker.py
Videos were not getting archived, so I added a cron job that runs the surf archiver cli to run video archiving.
> added a video archiving command

- export-ingester/export_ingester/sftp.py
- export-ingester/export_ingester/worker.py
- prince-archiver/prince_archiver/entrypoints/exporter/worker.py
Organised a retry schedule compatible with the risk of long term object store downtime. Current schedule waits 10sec, 10 min, 1 hour, 1 day and then another day.
- hardcoded a schedule in second
- retry queries this schedule
> Fixing retry
